In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
### create a dataset

x,y=make_classification(n_samples=1000, n_features=10, n_informative=4,n_classes=4, random_state=10) 

In [4]:
print(x)

[[ 1.90865023  1.05187946 -0.629882   ... -0.5494058  -1.67820264
  -0.0705014 ]
 [-0.32969449  1.65055589 -1.72260931 ... -1.56674526  1.24943224
   0.93609393]
 [ 0.616641   -1.01941743 -0.10712967 ... -1.29678395 -0.96324011
  -0.00988328]
 ...
 [-1.14249221 -1.16162347  0.10914175 ...  0.89930475  0.74475941
  -0.11327847]
 [ 1.98429289  1.53906134 -0.05345503 ...  0.80271784 -1.56236408
   0.18213623]
 [-1.47648096  1.08413676 -2.07579713 ...  2.44131852  2.08977574
  -0.38830745]]


In [5]:
y

array([1, 2, 0, 0, 2, 3, 0, 1, 3, 1, 1, 3, 1, 3, 2, 2, 3, 0, 1, 1, 1, 0,
       2, 2, 2, 2, 2, 0, 2, 2, 0, 3, 1, 3, 2, 3, 2, 2, 0, 1, 3, 2, 2, 2,
       0, 0, 3, 0, 0, 2, 3, 2, 0, 3, 0, 0, 3, 1, 3, 1, 0, 2, 2, 2, 2, 0,
       1, 2, 2, 3, 3, 3, 2, 3, 0, 0, 1, 0, 3, 3, 0, 2, 2, 1, 3, 2, 0, 3,
       0, 3, 3, 1, 0, 0, 0, 3, 1, 3, 0, 0, 0, 0, 3, 3, 2, 3, 2, 1, 0, 2,
       1, 3, 0, 0, 0, 1, 2, 3, 0, 2, 1, 2, 1, 3, 0, 3, 2, 1, 3, 2, 3, 1,
       0, 1, 2, 3, 0, 3, 1, 2, 3, 3, 1, 3, 0, 2, 1, 3, 1, 1, 0, 0, 2, 0,
       0, 0, 2, 0, 3, 3, 0, 3, 1, 0, 3, 3, 2, 1, 0, 1, 0, 3, 3, 2, 3, 2,
       1, 2, 3, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1, 2, 3, 1, 3, 2, 2, 3, 3, 2,
       0, 0, 2, 2, 1, 1, 0, 0, 3, 3, 3, 0, 2, 3, 3, 1, 2, 0, 0, 3, 2, 0,
       0, 2, 0, 2, 2, 2, 2, 3, 2, 2, 0, 0, 3, 0, 2, 2, 0, 2, 1, 3, 1, 3,
       3, 1, 3, 0, 3, 3, 0, 3, 3, 2, 2, 1, 1, 0, 1, 2, 0, 0, 0, 1, 3, 2,
       0, 0, 0, 3, 3, 3, 1, 0, 2, 0, 2, 2, 0, 3, 2, 0, 3, 1, 1, 3, 0, 3,
       1, 3, 1, 2, 3, 2, 2, 1, 2, 3, 2, 0, 1, 2, 3,

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30, random_state=35)

In [7]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')

In [8]:
logistic.fit(x_train,y_train)

/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [9]:
y_pred=logistic.predict(x_test)

In [10]:
y_pred

array([3, 2, 1, 0, 1, 0, 2, 2, 1, 1, 3, 2, 2, 0, 3, 3, 1, 3, 3, 3, 2, 0,
       3, 0, 2, 0, 2, 2, 2, 3, 3, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 1, 1,
       0, 0, 3, 0, 0, 1, 0, 0, 0, 2, 2, 3, 0, 2, 0, 0, 3, 0, 2, 1, 1, 2,
       0, 0, 3, 2, 2, 2, 2, 2, 1, 0, 1, 3, 0, 3, 2, 3, 3, 1, 2, 0, 3, 1,
       2, 2, 1, 0, 1, 1, 2, 2, 2, 2, 1, 0, 2, 1, 1, 3, 1, 3, 2, 2, 3, 1,
       2, 2, 2, 1, 1, 3, 1, 2, 0, 1, 3, 0, 1, 2, 3, 1, 2, 3, 3, 1, 1, 2,
       2, 1, 0, 1, 0, 3, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 3, 2, 1, 2, 2, 1,
       0, 3, 0, 3, 0, 0, 1, 0, 1, 3, 2, 1, 3, 1, 1, 2, 2, 1, 0, 3, 0, 0,
       3, 2, 1, 2, 0, 2, 1, 1, 2, 2, 3, 1, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 3, 0, 3, 2, 3, 3, 1, 3, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 2, 0, 1,
       1, 0, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1, 0, 1, 3, 2, 3, 0, 0, 1, 1, 0,
       3, 2, 2, 2, 1, 3, 3, 1, 2, 2, 2, 2, 0, 1, 3, 2, 0, 1, 2, 0, 3, 2,
       2, 2, 0, 2, 1, 0, 1, 1, 2, 0, 2, 2, 2, 1, 1, 3, 2, 0, 2, 1, 2, 2,
       2, 1, 2, 3, 2, 1, 1, 2, 1, 2, 0, 0, 3, 1])

In [11]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [12]:
score=accuracy_score(y_test,y_pred)
matrix=confusion_matrix(y_test,y_pred)
classification=classification_report(y_test,y_pred)
print(score)
print(matrix)
print(classification)

0.58
[[38  6  7 17]
 [ 3 50 15 11]
 [ 0  9 67  6]
 [24 13 15 19]]
              precision    recall  f1-score   support

           0       0.58      0.56      0.57        68
           1       0.64      0.63      0.64        79
           2       0.64      0.82      0.72        82
           3       0.36      0.27      0.31        71

    accuracy                           0.58       300
   macro avg       0.56      0.57      0.56       300
weighted avg       0.56      0.58      0.57       300



In [13]:
 ### hyperparameter tuning

model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.01,0.1]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'] 

In [14]:
params=dict(penalty=penalty, C=c_values, solver=solver)

In [15]:
### gridsearchcv(find the best parameter fit for the dataset)

from sklearn.model_selection import GridSearchCV, StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [16]:
grid.fit(x_train,y_train)

/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/envs/myenv/lib/python3.10/site-pack

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01, 0.1],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [17]:
y_test=grid.predict(x_test)

In [18]:
score=accuracy_score(y_test,y_pred)
matrix=confusion_matrix(y_test,y_pred)
classification=classification_report(y_test,y_pred)
print(score)
print(matrix)
print(classification)

0.9333333333333333
[[58  0  1  0]
 [ 0 76  3  4]
 [ 0  0 98  1]
 [ 7  2  2 48]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.94        59
           1       0.97      0.92      0.94        83
           2       0.94      0.99      0.97        99
           3       0.91      0.81      0.86        59

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



In [19]:
grid.best_params_

{'C': 1.0, 'penalty': 'l1', 'solver': 'saga'}

In [20]:
grid.best_score_

np.float64(0.5814285714285715)

In [21]:
 ### randomizes search cv

from sklearn.model_selection import RandomizedSearchCV
model=LogisticRegression()
random=RandomizedSearchCV(estimator=model, param_distributions=params, cv=5)

In [22]:
random.fit(x_train,y_train)
y_pred=random.predict(x_test)

/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1194, in fit
    solver = _ch

In [23]:
score=accuracy_score(y_test,y_pred)
matrix=confusion_matrix(y_test,y_pred)
classification=classification_report(y_test,y_pred)
print(score)
print(matrix)
print(classification)

0.9966666666666667
[[59  0  0  0]
 [ 0 83  0  0]
 [ 0  0 99  0]
 [ 0  1  0 58]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        59
           1       0.99      1.00      0.99        83
           2       1.00      1.00      1.00        99
           3       1.00      0.98      0.99        59

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300



In [24]:
random.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 10}

In [25]:
random.best_score_

np.float64(0.5757142857142857)